### ISSUE TITLE
Todo - Emails do sistema

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#7]
- [x] Motor de reservas
	 - [x] Notificação de multa de bookings
		 - [x] Operador
		 - [x] Cliente
	 - [x] Hotel
		 - [x] Cangooroo
			 - [x] Rollback confirmação reserva com custo cancelamento
		 - [x] Cliente
			 - [x] Confirmado
				 - [x] #100 
				 - [x] #101
			 - [x] Cancelado
				 - [x] #100 
				 - [x] #101
		 - [x] Fornecedor
			 - [x] Cancelado
				 - [x] #102
			 - [x] Confirmado
				 - [x] Hotel externo
					 - [x] #102
				 - [x] Hotel interno
					 - [x] #102
			 - [x] Operador
				 - [x] Confirmado		
				 	 - [x] #100 
				 	 - [x] #101
				 - [x] Cancelado
				 	 - [x] #100 
					 - [x] #101
	 - [X] Tour
		 - [X] Cliente
			 - [X] Confirmado
			 - [X] Cancelado
		 - [X] Operador
			 - [X] Confirmado
			 - [X] Cancelado
			 - [X] Alterado
	 - [X] Transfer
		 - [X] Cliente
			 - [X] Confirmado
			 - [X] Cancelado
		 - [X] Operador
			 - [X] Confirmado
			 - [X] Cancelado
			 - [X] Alterado
	 - [x] Adicional
		 - [x] Cliente
			 - [x] Confirmado
			 - [x] Cancelado
		 - [x] Operador
			 - [x] Confirmado
			 - [x] Cancelado
		 - [x] Fornecedor
			 - [x] Confirmado
				 - [x] #102
			 - [x] Cancelado
				 - [x] #102
	 - [x] Cartão de crédito
		 - [x] Erro no fluxo de cancelamento
		 - [x] Erro no fluxo de cancelamento por valor excedente
		 - [x] Erro no fluxo de pagamento
- [x] Front
	- [x] Senha alterada
		- [x] #103
	- [x] Recuperar senha
		- [x] #103
	- [x] Senha temporária
		- [x] #103
	- [x] Usuário alterado
	- [x] Usuário removido
	- [x] Usuário criado
- [x]  Hub
	- [x] Erro rollback confirmação reserva
	- [x] Erro rollback confirmação reserva cangooroo
- [x] Administrador
	- [x] Faturamento
		- [x] #104
